<?php
/** @package Optometry::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ContactlensMap.php");

/**
 * ContactlensDAO provides object-oriented access to the contactlens table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Optometry::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ContactlensDAO extends Phreezable
{
	/** @var int */
	public $Clensid;

	/** @var string */
	public $Name;

	/** @var float */
	public $Basecurve;

	/** @var float */
	public $Diameter;

	/** @var float */
	public $Sphere;

	/** @var int */
	public $Manufacturerid;



}
?>