<?php
/** @package Optometry::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("EyeMap.php");

/**
 * EyeDAO provides object-oriented access to the eye table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Optometry::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class EyeDAO extends Phreezable
{
	/** @var int */
	public $Patientid;

	/** @var string */
	public $Side;

	/** @var string */
	public $Color;

	/** @var int */
	public $Prescriptionid;



}
?>