<?php
/** @package Optometry::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PatientMap.php");

/**
 * PatientDAO provides object-oriented access to the patient table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Optometry::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PatientDAO extends Phreezable
{
	/** @var int */
	public $Patientid;

	/** @var string */
	public $Name;

	/** @var int */
	public $Prescriptionid1;

	/** @var int */
	public $Prescriptionid2;

	/** @var string */
	public $Phone1;

	/** @var string */
	public $Phone2;

	/** @var string */
	public $Housenumber;

	/** @var string */
	public $Street;

	/** @var string */
	public $City;

	/** @var string */
	public $State;

	/** @var int */
	public $Zipcode;



}
?>