<?php
/** @package Optometry::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PrescriptionMap.php");

/**
 * PrescriptionDAO provides object-oriented access to the prescription table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Optometry::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PrescriptionDAO extends Phreezable
{
	/** @var int */
	public $Prescriptionid;

	/** @var int */
	public $Optometristid;

	/** @var int */
	public $Clensid;

	/** @var int */
	public $Glensid;



}
?>